export const projects = [
    {
        id: 1,
        title: "EscapeTime",
        slug: "escapetime",
        paragraph: "Timer réalisé pour un Escape Game",
        description:
            "Dans le cadre de l'Escape Game 'Angel's Game', j'ai développé un timer personnalisé visant à enrichir l'expérience des joueurs et à faciliter la gestion du temps par les maîtres du jeu. Ce chronomètre, conçu avec JavaScript et Electron, est déployé sur deux interfaces distinctes. L'une est destinée aux joueurs dans la salle de jeu sur une télévision qui affiche le temps restant, offrant aux participants une visualisation claire de leur progression et renforçant l'immersion. L'autre interface est réservée aux maîtres du jeu sur leur écran d'ordinateur, leur permettant de contrôler le temps, de lancer des effets sonores et de gérer les paramètres du jeu.",
        img: "timer.jpg",
        bgColorLeft: "#2b3231",
        bgColorRight: "#f1f1f1",
        bgColor: "#2b3231",
        class: "w-full h-full object-cover",
        githubLink: "https://github.com/MattBuchs/EscapeGame-Timer",
        projectLink: null,
    },
    {
        id: 2,
        title: "NutriScaP",
        slug: "nutriscap",
        paragraph:
            "Réalisation d'une application mobile de scan de produits de supermarché",
        description:
            "Dans le cadre d'un projet client, j'ai développé une application mobile en React Native permettant aux utilisateurs de scanner les produits de supermarché afin d'accéder à des informations détaillées telles que le Nutri-Score, la liste des ingrédients et les allergènes. Les utilisateurs ont également la possibilité d'évaluer les produits et de laisser des commentaires. L'application offre une interface intuitive et ergonomique, garantissant une expérience utilisateur fluide et agréable. (Bientôt disponible sur le Play Store)",
        img: "phone-scap.png",
        bgColorLeft: "#f1f1f1",
        bgColorRight: "#3c6620",
        bgColor: "#3c6620",
        class: "w-[300px] h-auto absolute top-20 left-5 mx-16",
        githubLink: null,
        projectLink: null,
    },
    {
        id: 3,
        title: "O'Gaming",
        slug: "o-gaming",
        paragraph:
            "App de rapport de bugs pour aider les développeurs de jeux vidéos",
        description:
            "Dans le cadre d'un projet collaboratif réunissant une équipe de quatre développeurs, nous avons conçu et développé une application web dédiée à la collecte et à la gestion des rapports de bugs pour les jeux vidéo. Cette plateforme offre aux joueurs la possibilité de signaler aisément les anomalies rencontrées dans leurs jeux favoris, tandis que les développeurs peuvent consulter ces rapports pour apporter les corrections nécessaires. ",
        img: "OGaming.webp",
        bgColorLeft: "#620c03",
        bgColorRight: "#f1f1f1",
        bgColor: "#620c03",
        class: "w-full h-full object-contain mx-10 mb-52",
        githubLink: "https://github.com/MattBuchs/projet-o-gaming-back",
        projectLink: null,
    },
    {
        id: 4,
        title: "Angel's Game",
        slug: "angels-game",
        paragraph: "Réalisation d'un site web pour un Escape Game",
        description:
            "Dans le cadre du projet Angel's Game, un Escape Game situé à Arçon près de Pontarlier, j'ai développé un site web complet en utilisant Next.js, visant à améliorer l'expérience utilisateur et à faciliter la gestion des réservations. Les utilisateurs peuvent réserver directement les différentes salles de l'Escape Game via le site, simplifiant ainsi le processus de réservation. Chaque salle est décrite avec son scénario, son niveau de difficulté, le nombre de joueurs requis et le taux de réussite, permettant aux visiteurs de choisir l'expérience qui leur convient le mieux.",
        img: "illustration-angelsgame.png",
        bgColorLeft: "#f1f1f1",
        bgColorRight: "#167038",
        bgColor: "#167038",
        class: "w-1/5 h-auto absolute top-32 left-14 rounded shadow",
        githubLink: null,
        projectLink: "https://www.angelsgame.fr",
    },
    {
        id: 5,
        title: "MemKeyPass",
        slug: "memkeypass",
        paragraph: "Gestionnaire de mots de passe sécurisé",
        description:
            "J'ai développé une application de gestion de mots de passe sécurisée nommée MemKeyPass, utilisant Next.js avec une base de données Supabase. L'application permet aux utilisateurs de stocker, organiser et gérer leurs mots de passe de manière sécurisée. Elle intègre des fonctionnalités telles que la génération de mots de passe forts, le chiffrement des données sensibles et une interface utilisateur intuitive pour faciliter la gestion des informations de connexion.",
        img: "illustration-memkeypass.png",
        bgColorLeft: "#00786f",
        bgColorRight: "#f1f1f1",
        bgColor: "#00786f",
        class: "w-2/5 h-2/3 object-contain absolute top-24 right-24",
        githubLink: null,
        projectLink: "https://memkeypass.fr",
    },
    {
        id: 6,
        title: "PlaySkroma",
        slug: "playskroma",
        paragraph: "Projet d'un site repertoriant plusieurs jeux de société",
        description:
            "J'ai entrepris le développement d'un site web dédié aux jeux de société en ligne, actuellement en phase de développement. Ce projet, construit avec les technologies JavaScript, React et Node.js, propose pour l'instant deux jeux classiques : les dames et le morpion. Mon objectif est d'enrichir progressivement la plateforme en ajoutant une variété d'autres jeux de société, offrant ainsi aux utilisateurs une expérience ludique diversifiée et accessible en ligne.",
        img: "jeux-plateau.jpg",
        bgColorLeft: "#f1f1f1",
        bgColorRight: "#563f31",
        bgColor: "#563f31",
        class: "w-full h-full object-cover",
        githubLink: "https://github.com/MattBuchs/play-skroma",
        projectLink: "https://play-skroma.fr/",
    },
];
